### ISSUE TITLE
Build error CustomTypeOne LoopPatches latest dev

### ISSUE THREAD

**Issue by ViTuDia** [loopandlearn/customization#12]
Next to that PR 2002 gives an error with the latest dev commit, also building with browser the CustomTypeOne LoopPatches give an error with the latest dev commit. This happened after opting out 2002.

**Comment by marionbarker** [comment]
Thank you for the report.

**Comment by bjorkert** [comment]
PR 2002 has been updated to work with dev. CTO LoopPatches remains to be fixed.

**Comment by ViTuDia** [comment]
Well, there seems something else wrong, probably with my settings. I opted out CustumTypeOne Looppatches in the workflow file, cause I thought that would give me the error during the Fastlane Build & Archive process. But without having the CTO patches in the build process it is still giving a build error. So probably (might be) there is nothing wrong with the CTO patches. 

Sorry for the confusion. Too fast conclusions. 

ViTuDia/LoopWorkspace. Run #54 contains the error. No clue what it can be :(

**Comment by bjorkert** [comment]
It was not obvious to me what the problem is, @dnzxy do you understand?

**Comment by ViTuDia** [comment]
I probably will do a refresh fork of everything tomorrow. Fastest solution I guess. Thanks for looking.

**Comment by bjorkert** [comment]
It appears dev is currently broken when it comes to browser build.

**Comment by ViTuDia** [comment]
And CTO patches (when set up in the workflow file) give an error as well, so well, this issue remains too, despite the broken dev.

**Comment by dnzxy** [comment]
That could very well be connected to the broken dev build. One of the commits from yesterday migrated some modules to other paths - if CTO patches are referencing the old module locations in the patch file that may be the issue.

**Comment by marionbarker** [comment]
The customization (apply to charts in LoopKit that used to reside in Loop) has been updated with PR #13.

This issue is closed.

Problems with browser build are independent.  Please see zulipchat: https://loop.zulipchat.com/#narrow/stream/144182-development/topic/Widget.20extension.20bundle.20id.20name.20change
