### ISSUE TITLE
Profiles (PR 2002) does not work with latest dev. 

### ISSUE THREAD

**Issue by ViTuDia** [loopandlearn/customization#17]
Seems that Profiles (PR 2002) patch does not work with latest dev commit 7236425. 

Fails building while customizing Loop during the build proces. Opting out 2002 works fine and Loop dev builds.

**Comment by marionbarker** [comment]
Thanks for the notification. We will work on this.

**Comment by bjorkert** [comment]
The customization is now updated for latest dev.
